import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { Modal } from '../ui/Modal';
import { Button } from '../ui/Button';
import { useAnalytics } from '../../hooks/useAnalytics';
import { useToast } from '../../context/ToastContext';
import { useTheme } from '../../context/ThemeContext';
import { tokens } from '../../styles/tokens';
import { Shield, TrendingUp, Cpu } from 'lucide-react';

export const ReviewAuditModal = ({ isOpen, onClose }) => {
  const { colors } = useTheme();

  const AuditRow = ({ icon: Icon, label, value, color }) => (
    <View style={[styles.auditRow, { borderBottomColor: colors.border }]}>
      <View style={[styles.iconBox, { backgroundColor: colors.surfaceElevated }]}>
        <Icon size={16} color={color || colors.textSecondary} />
      </View>
      <Text style={[styles.auditLabel, { color: colors.textSecondary }]}>{label}</Text>
      <Text style={[styles.auditValue, { color: colors.textPrimary }]}>{value}</Text>
    </View>
  );

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Strategy Audit Report" style={{ width: 450 }}>
      <Text style={[styles.body, { color: colors.textSecondary }]}>
        Comprehensive analysis generated by Wealth Curator AI for Q3 rebalancing strategy.
      </Text>

      <View style={[styles.metricsContainer, { backgroundColor: colors.surfaceElevated, borderColor: colors.border }]}>
        <AuditRow icon={Shield} label="Risk Assessment" value="Moderate (7.2/10)" color={tokens.colors.warning} />
        <AuditRow icon={TrendingUp} label="Performance vs Benchmark" value="+3.4% vs S&P 500" color={tokens.colors.green} />
        <AuditRow icon={Cpu} label="AI Confidence Score" value="92%" color={tokens.colors.primary} />
      </View>
      
      <View style={styles.actions}>
        <Button variant="ghost" onPress={onClose}>
          Close
        </Button>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  body: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 20,
  },
  metricsContainer: {
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 24,
  },
  auditRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
  },
  iconBox: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  auditLabel: {
    flex: 1,
    fontSize: 13,
  },
  auditValue: {
    fontSize: 14,
    fontWeight: '600',
  },
  actions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  }
});
